"""MCP tools for archiving and fetching purchase receipts."""

import json
from datetime import date

from mcp.schemas.tools import MCPTool, MCPToolDefinition, MCPToolResult

from ledger.mcp_tools._common import _fail, _ok, ledger_path, with_middleware
from ledger.receipts import Receipt, ReceiptItem, add_receipt, get_receipts_by_ids


async def handle_add_receipt(args: dict) -> MCPToolResult:
    try:
        receipt = Receipt(
            currency=args["currency"],
            store_name=args.get("store_name"),
            store_location=args.get("store_location"),
            items=[
                ReceiptItem(
                    name=item["name"],
                    name_inf=item.get("name_inf"),
                    qty=item.get("qty", 1.0),
                    unit=item.get("unit", "pcs"),
                    amount=item["amount"],
                )
                for item in args["items"]
            ],
        )
        receipt_id = add_receipt(
            ledger_path(),
            date.fromisoformat(args["date"]),
            receipt,
        )
    except Exception as exc:
        return _fail("add_receipt", exc)

    return _ok(
        f"Receipt added with id {receipt_id}",
        {
            "id": receipt_id,
            "date": args["date"],
            "store_name": args.get("store_name"),
            "store_location": args.get("store_location"),
        },
    )


async def handle_get_receipts_by_ids(args: dict) -> MCPToolResult:
    try:
        receipts = get_receipts_by_ids(ledger_path(), args["ids"])
    except Exception as exc:
        return _fail("get_receipts_by_ids", exc)

    payload = [receipt.model_dump(mode="json") for receipt in receipts]
    return _ok(
        json.dumps(payload, ensure_ascii=False),
        {"receipts": payload, "count": len(payload)},
    )



add_receipt_description = """Archive a purchase receipt as one JSON record in receipts/<YEAR>.jsonl (year from the receipt date). Always returns a confirmation message with the generated receipt id (format YYYY-MM-DD-<hex>). The id is generated by the tool — do not pass one.

when there's a discount record/ position for an item -- merge them.

Use for purchase evidence: amount, merchant, item lines, and each line's unit (pcs, kg, lt). Capture what the receipt itself shows; keep item names short and store names consistent so receipts group by store."""


get_receipts_by_ids_description = """Fetch stored receipts by id from receipts/<YEAR>.jsonl. All-or-nothing: if any id is missing the call fails and the error names every missing id. Returns the archive objects (id, date, currency, store, items) in the same order as the request.

Ids are those returned by add_receipt (format YYYY-MM-DD-<hex>); the date prefix selects the year file. Do not invent ids."""


RECEIPT_TOOLS: tuple[MCPTool, ...] = (
    MCPTool(
        func=with_middleware(handle_add_receipt),
        definition=MCPToolDefinition(
            name="add_receipt",
            description=add_receipt_description,
            inputSchema={
                "type": "object",
                "properties": {
                    "date": {
                        "type": "string",
                        "format": "date",
                        "description": "ISO 8601 receipt date (YYYY-MM-DD), e.g. 2026-08-21. Its year selects receipts/<YEAR>.jsonl.",
                    },
                    "currency": {
                        "type": "string",
                        "description": "Receipt currency code, e.g. 'EUR', 'USD'.",
                    },
                    "store_name": {
                        "type": "string",
                        "description": "Merchant/store name",
                    },
                    "store_location": {
                        "type": "string",
                        "description": "Optional store location (city, address).",
                    },
                    "items": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "type": "string",
                                    "description": "Verbatim OCR string from the receipt, never modified.",
                                },
                                "name_inf": {
                                    "type": "string",
                                    "description": "Guess at the real product name (may be wrong); omit if unknown.",
                                },
                                "qty": {
                                    "type": "number",
                                    "description": "Quantity of this line; defaults to 1.",
                                },
                                "unit": {
                                    "type": "string",
                                    "description": "Unit of the quantity (pcs, kg, lt, etc.). Defaults to 'pcs' when omitted.",
                                },
                                "amount": {
                                    "type": "number",
                                    "description": "Total price for this line in the receipt currency, e.g. 3.5.",
                                },
                            },
                            "required": ["name", "amount"],
                            "additionalProperties": False,
                        },
                        "description": "Item lines from the receipt, one per purchased line.",
                    },
                },
                "required": ["date", "currency", "items"],
            },
        ),
    ),
    MCPTool(
        func=with_middleware(handle_get_receipts_by_ids),
        definition=MCPToolDefinition(
            name="get_receipts_by_ids",
            description=get_receipts_by_ids_description,
            inputSchema={
                "type": "object",
                "properties": {
                    "ids": {
                        "type": "array",
                        "minItems": 1,
                        "items": {"type": "string"},
                        "description": "Receipt ids as returned by add_receipt (format YYYY-MM-DD-<hex>). All must exist.",
                    },
                },
                "required": ["ids"],
            },
        ),
    ),
)
