"""Append receipts to the yearly ``receipts/<YEAR>.jsonl`` archive.

A receipt is a structured ``Receipt`` model — currency, store, and item
lines — stored as one JSON value per line, routed into the yearly file by
its date. Every stored record carries the receipt's ``date`` and a
generated ``id`` (never trusted from the caller), so each line is
self-contained and the archive is append-only.
"""

import json
import uuid
from datetime import date as _date
from pathlib import Path
from typing import Optional, List, Union

from pydantic import BaseModel, Field

from .layout import KIND_RECEIPT, resolve_target


class ReceiptItem(BaseModel):
    name: str = Field(..., description="Verbatim OCR string, never modified.")
    name_inf: Optional[str] = Field(default=None, description="Guess at the real product name, may be wrong.")
    qty: float = 1.0
    amount: float = Field(..., description="Total price")


class Receipt(BaseModel):
    id: Optional[str] = Field(default=None, description="ID generated by add_receipt on append. Do not fill manually.")
    currency: str
    store_name: Optional[str]
    store_location: Optional[str]
    items: List[ReceiptItem]


def add_receipt(
    path: Union[str, Path],
    date: _date,
    receipt: Receipt,
) -> str:
    """Append ``receipt`` to ``receipts/<YEAR>.jsonl`` and return its ``id``.

    ``id`` is the only key on the stored record generated here; a value left
    on ``Receipt.id`` is ignored and replaced. ``date`` is stored as-is
    (``YYYY-MM-DD``) and its year routes the entry into
    ``<ledger dir>/receipts/<YEAR>.jsonl`` (created on first use); entries
    are appended with a trailing newline, one JSON value per line.

    Args:
        path: The ledger root (a directory) or the ledger file itself, used
            to resolve where the receipt is written: its parent directory
            holds ``receipts/<YEAR>.jsonl``.
        date: A ``datetime.date``; used for routing (year) and stored on the
            record.
        receipt: The ``Receipt`` model describing the purchase. Not mutated;
            its ``id`` is ignored in favour of the generated one.

    Returns:
        The generated ``id`` string assigned to the stored receipt: the date
        (``YYYY-MM-DD``) prefixed to a short random hex hash, e.g.
        ``2026-08-21-53f7acbb``.
    """
    target = resolve_target(path, KIND_RECEIPT, date=date)
    receipt_id = f"{date.isoformat()}-{uuid.uuid4().hex[:8]}"
    stored = {"date": date.isoformat(), **receipt.model_dump(exclude={"id"}), "id": receipt_id}
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as f:
        f.write(json.dumps(stored, ensure_ascii=False) + "\n")
        f.flush()

    return receipt_id