"""MCP tool for appending transactions to the ledger."""

from datetime import date

from mcp.schemas.tools import MCPTool, MCPToolDefinition, MCPToolResult

from ledger.mcp_tools._common import _fail, _ok, ledger_path, with_middleware
from ledger.transactions import add_transaction, format_transaction


def _posting_spec(spec: dict) -> dict:
    """Translate a JSON-Schema posting dict into an internal posting spec.

    The tool's public schema uses flat ``cost_*``/``price_*`` keys and an
    explicit ``elided`` flag; :func:`make_posting` consumes a nested
    ``cost``/``price`` dict and ``number=None`` for the elided balancing leg.
    """
    posting = {"account": spec["account"]}
    if spec.get("elided"):
        posting["number"] = None
    else:
        posting["number"] = spec["number"]
        posting["currency"] = spec["currency"]

    cost: dict = {}
    if "cost_number" in spec:
        cost["number"] = spec["cost_number"]
        cost["currency"] = spec["cost_currency"]
    if "cost_date" in spec:
        cost["date"] = date.fromisoformat(spec["cost_date"])
    if "cost_label" in spec:
        cost["label"] = spec["cost_label"]
    if cost:
        posting["cost"] = cost

    if "price_number" in spec:
        posting["price"] = {
            "number": spec["price_number"],
            "currency": spec["price_currency"],
        }

    if "flag" in spec:
        posting["flag"] = spec["flag"]
    if "meta" in spec:
        posting["meta"] = spec["meta"]
    return posting


async def handle_add_transaction(args: dict) -> MCPToolResult:
    # The "agent" tag lets every transaction written through the tool be
    # attributed back to the agent that requested it.
    tags = set(args.get("tags") or [])
    tags.add("agent")

    meta = dict(args.get("meta") or {})
    receipt_ids = args.get("receipt_ids")
    if receipt_ids:
        meta["receipt_ids"] = " ".join(receipt_ids)

    try:
        txn, errors = add_transaction(
            ledger_path(),
            date.fromisoformat(args["date"]),
            args["narration"],
            [_posting_spec(p) for p in args["postings"]],
            payee=args.get("payee"),
            flag=args.get("flag", "*"),
            tags=tags,
            links=set(args["links"]) if args.get("links") else None,
            meta=meta,
        )
    except Exception as exc:
        return _fail("add_transaction", exc)

    return _ok(
        format_transaction(txn).rstrip(),
        {
            "date": txn.date.isoformat(),
            "narration": txn.narration,
            "payee": txn.payee,
            "flag": txn.flag,
            "postings": [p.account for p in txn.postings],
            "errors": errors,
        },
        isError=bool(errors),
    )


add_transaction_description = """Append a validated Beancount transaction to the ledger. Staged and validated before anything writes; on error nothing is written and errors are returned.

Postings must sum to zero unless exactly one has elided=true (auto-computed to balance).

Examples:

1) Ordinary expense — no cost/price fields:
   Beancount:
     2024-02-01 * "Cafe" "Coffee"
       Expenses:Food:Coffee   3.50 EUR
       Assets:Checking
   Schema:
     postings: [
       {account: "Expenses:Food:Coffee", number: "3.50", currency: "EUR"},
       {account: "Assets:Checking", elided: true}
     ]

2) Buying a tracked lot — cost_* fields record per-unit acquisition cost:
   Beancount:
     2024-02-01 * "Broker" "Buy AAPL"
       Assets:Brokerage:AAPL   10 AAPL {150.00 USD, "lot-a"}
       Assets:Brokerage:Cash  -1500.00 USD
   Schema:
     postings: [
       {account: "Assets:Brokerage:AAPL", number: "10", currency: "AAPL", cost_number: "150.00", cost_currency: "USD", cost_label: "lot-a"},
       {account: "Assets:Brokerage:Cash", number: "-1500.00", currency: "USD"}
     ]

3) Currency conversion — price_* fields annotate FX value, no lot tracking:
   Beancount:
     2024-02-01 * "Transfer"
       Assets:EUR:Checking   -100.00 EUR @ 1.08 USD
       Assets:USD:Checking    108.00 USD
   Schema:
     postings: [
       {account: "Assets:EUR:Checking", number: "-100.00", currency: "EUR", price_number: "1.08", price_currency: "USD"},
       {account: "Assets:USD:Checking", number: "108.00", currency: "USD"}
     ]

Use cost_* only for tracked lots (stocks/crypto/inventory) you will later dispose of by lot. Use price_* only to annotate an FX rate on a plain conversion. Leave both blank for cash movements — the default case.

Link purchase evidence with receipt_ids: pass the receipt ids returned by the add_receipt tool (format YYYY-MM-DD-<hex>) — those ids are generated by add_receipt, never invented — and they are stored in the transaction meta as receipt_ids."""


TRANSACTION_TOOLS: tuple[MCPTool, ...] = (
    MCPTool(
        func=with_middleware(handle_add_transaction),
        definition=MCPToolDefinition(
            name="add_transaction",
            description=add_transaction_description,
            inputSchema={
                "type": "object",
                "properties": {
                    "date": {
                        "type": "string",
                        "format": "date",
                        "description": "ISO 8601 transaction date (YYYY-MM-DD), e.g. 2024-02-01.",
                    },
                    "narration": {
                        "type": "string",
                        "description": "Required human description shown on the directive row, e.g. \"Coffee at cafe\".",
                    },
                    "payee": {
                        "type": "string",
                        "description": "Optional merchant/counterparty displayed before the narration; keep it consistent so transactions group by who was paid.",
                    },
                    "flag": {
                        "type": "string",
                        "enum": ["*", "!"],
                        "description": "Transaction flag; '*' = cleared/normal (default), '!' = pending attention. Overridable per posting.",
                    },
                    "tags": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Optional tags to attach (rendered as #tag); the tool always adds the agent tag.",
                    },
                    "links": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Optional links to related transactions (rendered as ^link).",
                    },
                    "meta": {
                        "type": "object",
                        "additionalProperties": {"type": "string"},
                        "description": "Optional transaction-level metadata as Key: Value, e.g. {\"id\": \"seq-1\"}.",
                    },
                    "receipt_ids": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Receipt IDs backing this transaction, as returned by the add_receipt tool (format YYYY-MM-DD-<hex>). Stored in the transaction meta as a space-separated receipt_ids string. Link every transaction to the receipt(s) that evidence it.",
                    },
                    "postings": {
                        "type": "array",
                        "minItems": 1,
                        "items": {
                            "type": "object",
                            "properties": {
                                "account": {
                                    "type": "string",
                                    "description": "Full Beancount account name, e.g. 'Expenses:Food:Coffee' or 'Assets:Checking:BPI'.",
                                },
                                "elided": {
                                    "type": "boolean",
                                    "default": False,
                                    "description": "Set true to auto-compute this posting's amount so the transaction balances. At most one posting per transaction may set this. When true, omit number and currency.",
                                },
                                "number": {
                                    "type": "string",
                                    "description": "Amount of units moved, as a decimal string (e.g. '12.50'). Positive or negative per normal Beancount sign convention. Required unless elided=true.",
                                },
                                "currency": {
                                    "type": "string",
                                    "description": "Commodity code for this posting's amount, e.g. 'EUR', 'USD', 'AAPL'. Required unless elided=true.",
                                },
                                "cost_number": {
                                    "type": "string",
                                    "description": "Per-unit acquisition cost, decimal string, e.g. '150.00'. Only for tracked-lot postings (stocks, crypto, inventory). Omit for ordinary cash postings.",
                                },
                                "cost_currency": {
                                    "type": "string",
                                    "description": "Currency the cost_number is denominated in, e.g. 'USD'. Required if cost_number is set.",
                                },
                                "cost_date": {
                                    "type": "string",
                                    "format": "date",
                                    "description": "Date the lot was originally acquired, if different from this transaction's date. Used to match which lot a later reducing posting draws down. Defaults to the transaction date if omitted.",
                                },
                                "cost_label": {
                                    "type": "string",
                                    "description": "Optional identifier to disambiguate this lot from others at the same cost and date.",
                                },
                                "price_number": {
                                    "type": "string",
                                    "description": "FX conversion rate for this posting's amount, decimal string. Not a tracked lot — just annotates what the amount was worth in another currency at transaction time.",
                                },
                                "price_currency": {
                                    "type": "string",
                                    "description": "Currency the price_number is denominated in. Required if price_number is set.",
                                },
                                "flag": {
                                    "type": "string",
                                    "enum": ["*", "!"],
                                    "description": "Overrides the transaction-level flag for this posting only.",
                                },
                                "meta": {
                                    "type": "object",
                                    "additionalProperties": {"type": "string"},
                                },
                            },
                            "required": ["account"],
                            "additionalProperties": False,
                        },
                        "description": "Every account and amount moved. Postings must balance to zero unless exactly one posting has elided=true. Validation fails closed: on any imbalance or malformed posting nothing is written and errors are returned. See tool description above for cost vs price examples.",
                    },
                },
                "required": ["date", "narration", "postings"],
            },
        ),
    ),
)
