"""Yearly ``receipts/<YEAR>.jsonl`` archive: append and fetch by id.

A receipt is a structured ``Receipt`` model — currency, store, and item
lines — stored as one JSON value per line, routed into the yearly file by
its date. Every stored record carries the receipt's ``date`` and a
generated ``id`` (never trusted from the caller), so each line is
self-contained and the archive is append-only. ``get_receipts_by_ids``
loads those records back; missing ids fail the whole call.
"""

import json
import re
import uuid
from collections.abc import Sequence
from datetime import date as _date
from pathlib import Path
from typing import Optional, List, Union

from pydantic import BaseModel, Field

from .layout import KIND_RECEIPT, resolve_target

_ID_DATE = re.compile(r"^(\d{4}-\d{2}-\d{2})-")


class ReceiptItem(BaseModel):
    name: str = Field(..., description="Verbatim OCR string, never modified.")
    name_inf: Optional[str] = Field(default=None, description="Inferred human-readable product name, english")
    qty: float = 1.0
    unit: str = Field(default="pcs", description="For qty: pcs, kg, lt, etc.")
    amount: float = Field(..., description="Total price")


class Receipt(BaseModel):
    id: Optional[str] = Field(default=None, description="ID generated by add_receipt on append. Do not fill manually.")
    date: Optional[_date] = Field(default=None, description="Archive date (YYYY-MM-DD). Filled on stored receipts; do not pass to add_receipt.")
    currency: str
    store_name: Optional[str]
    store_location: Optional[str]
    items: List[ReceiptItem]


def add_receipt(
    path: Union[str, Path],
    date: _date,
    receipt: Receipt,
) -> str:
    """Append ``receipt`` to ``receipts/<YEAR>.jsonl`` and return its ``id``.

    ``id`` is the only key on the stored record generated here; a value left
    on ``Receipt.id`` is ignored and replaced. ``date`` is stored as-is
    (``YYYY-MM-DD``) and its year routes the entry into
    ``<ledger dir>/receipts/<YEAR>.jsonl`` (created on first use); entries
    are appended with a trailing newline, one JSON value per line.

    Args:
        path: The ledger root (a directory) or the ledger file itself, used
            to resolve where the receipt is written: its parent directory
            holds ``receipts/<YEAR>.jsonl``.
        date: A ``datetime.date``; used for routing (year) and stored on the
            record.
        receipt: The ``Receipt`` model describing the purchase. Not mutated;
            its ``id`` is ignored in favour of the generated one.

    Returns:
        The generated ``id`` string assigned to the stored receipt: the date
        (``YYYY-MM-DD``) prefixed to a short random hex hash, e.g.
        ``2026-08-21-53f7acbb``.
    """
    target = resolve_target(path, KIND_RECEIPT, date=date)
    receipt_id = f"{date.isoformat()}-{uuid.uuid4().hex[:8]}"
    stored = {"date": date.isoformat(), **receipt.model_dump(exclude={"id", "date"}), "id": receipt_id}
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as f:
        f.write(json.dumps(stored, ensure_ascii=False) + "\n")
        f.flush()

    return receipt_id


def get_receipts_by_ids(
    path: Union[str, Path],
    ids: Sequence[str],
) -> List[Receipt]:
    """Load stored receipts by id. Fail if any id is missing.

    Each id's ``YYYY-MM-DD`` prefix selects ``receipts/<YEAR>.jsonl``.
    Results follow ``ids`` order. A missing id (unknown, malformed, or
    in a year file that does not contain it) fails the whole call and
    the error names every id that was not found.

    Args:
        path: Ledger root or ledger file; same as ``add_receipt``.
        ids: Receipt ids as returned by ``add_receipt``
            (``YYYY-MM-DD-<hex>``). Must not be empty.

    Returns:
        One ``Receipt`` per requested id, with ``id`` and ``date`` filled
        from the archive.

    Raises:
        ValueError: ``ids`` is empty.
        LookupError: One or more ids were not found. Message lists them.
    """
    if not ids:
        raise ValueError("ids must not be empty")

    wanted = list(ids)
    by_year: dict[int, set[str]] = {}
    for receipt_id in wanted:
        match = _ID_DATE.match(receipt_id)
        if match is None:
            continue
        year = int(match.group(1)[:4])
        by_year.setdefault(year, set()).add(receipt_id)

    found: dict[str, Receipt] = {}
    for year, year_ids in by_year.items():
        remaining = year_ids - found.keys()
        if not remaining:
            continue
        target = resolve_target(path, KIND_RECEIPT, date=_date(year, 1, 1))
        if not target.is_file():
            continue
        with target.open(encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
                receipt_id = record.get("id")
                if receipt_id not in remaining:
                    continue
                found[receipt_id] = Receipt.model_validate(record)
                remaining.discard(receipt_id)
                if not remaining:
                    break

    missing = list(dict.fromkeys(rid for rid in wanted if rid not in found))
    if missing:
        raise LookupError("receipts not found: " + ", ".join(missing))
    return [found[rid] for rid in wanted]
